### ISSUE TITLE
link error in part9: "Building your first DApp"

### ISSUE THREAD

**Issue by jnaulty** [bwonymph/TezosCapstone#1]
While going through this course, I found a link error for the `Building your first DApp` section.

The link: http://www.liquidity-lang.org/zeronet/ should be: http://www.liquidity-lang.org/edit/

The source page:
https://github.com/bwonymph/TezosCapstone/blob/master/curriculum/sources/part9.rst.txt

**Comment by bwonymph** [comment]
Thanks for finding the error, has been corrected.
